In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder



In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [5]:
df.sample(5)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
11          M        15.78         17.89          103.60      781.0   
52          B        11.94         18.24           75.71      437.6   
79          B        12.86         18.00           83.19      506.3   
207         M        17.01         20.26          109.70      904.3   
436         B        12.87         19.54           82.67      509.2   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
11           0.09710           0.12920         0.09954              0.06606   
52           0.08261           0.04751         0.01972              0.01349   
79           0.09934           0.09546         0.03889              0.02315   
207          0.08772           0.07304         0.06950              0.05390   
436          0.09136           0.07883         0.01797              0.02090   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
11          0.1842  ...         20.42          27.28           136.50   
52          0.1868  ...         13.10          21.33            83.67   
79          0.1718  ...         14.24          24.82            91.88   
207         0.2026  ...         19.80          25.05           130.00   
436         0.1861  ...         14.45          24.38            95.14   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
11       1299.0            0.1396            0.56090          0.39650   
52        527.2            0.1144            0.08906          0.09203   
79        622.1            0.1289            0.21410          0.17310   
207      1210.0            0.1111            0.14860          0.19320   
436       626.9            0.1214            0.16520          0.07127   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
11                0.18100          0.3792                  0.10480  
52                0.06296          0.2785                  0.07408  
79                0.07926          0.2779                  0.07918  
207               0.10960          0.3275                  0.06469  
436               0.06384          0.3313                  0.07735  

[5 rows x 31 columns]

In [6]:
  # train_test_split

test = df.iloc[:,1:]
train = df.iloc[:,0]


X_train,X_test,y_train,y_test = train_test_split(test,train, test_size=0.2)

In [7]:
y_train

486    B
230    M
57     M
473    B
525    B
      ..
127    M
441    M
132    M
390    B
509    M
Name: diagnosis, Length: 455, dtype: object

In [8]:
# scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [9]:
X_train

array([[ 0.19076933, -0.53906975,  0.13579214, ..., -0.5152897 ,
        -0.7516469 , -1.07340406],
       [ 0.88944175, -0.03447822,  0.94128019, ...,  2.18369594,
         0.3746312 ,  0.45227176],
       [ 0.21106272,  0.53347009,  0.19203779, ...,  1.09655765,
         1.38897034,  1.61525142],
       ...,
       [ 0.6314258 ,  0.52215637,  0.63906477, ...,  0.296154  ,
         1.01354431, -0.44023312],
       [-1.07901706, -1.58671942, -1.05879826, ..., -0.68886382,
         0.0784235 , -0.37648277],
       [ 0.4284919 ,  1.06747726,  0.53832629, ...,  1.60102662,
         0.20930597,  1.44813885]])

In [10]:
y_train

486    B
230    M
57     M
473    B
525    B
      ..
127    M
441    M
132    M
390    B
509    M
Name: diagnosis, Length: 455, dtype: object

In [11]:
#label encoding

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,

In [13]:
y_test

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1])

In [14]:
# Numpy array to pytorch tensors

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
Y_train_tensor = torch.from_numpy(y_train)
Y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_train_tensor.shape

torch.Size([455, 30])

In [17]:
X_train_tensor

tensor([[ 0.1908, -0.5391,  0.1358,  ..., -0.5153, -0.7516, -1.0734],
        [ 0.8894, -0.0345,  0.9413,  ...,  2.1837,  0.3746,  0.4523],
        [ 0.2111,  0.5335,  0.1920,  ...,  1.0966,  1.3890,  1.6153],
        ...,
        [ 0.6314,  0.5222,  0.6391,  ...,  0.2962,  1.0135, -0.4402],
        [-1.0790, -1.5867, -1.0588,  ..., -0.6889,  0.0784, -0.3765],
        [ 0.4285,  1.0675,  0.5383,  ...,  1.6010,  0.2093,  1.4481]],
       dtype=torch.float64)

## Defning The Model

In [43]:
  class MySimpleNN():
    def __init__(self,X):

      self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
      self.bias = torch.zeros(1, dtype=torch.float64,requires_grad=True)

    def forward(self,X):
      z = torch.matmul(X,self.weights) + self.bias
      y_pred = torch.sigmoid(z)
      return y_pred

    def loss_function(self, y_pred, y):
       # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

## Important Paramaters

In [62]:
learning_rate = 0.01
epochs = 25

## Traning Pipeline

In [63]:
# create model
model = MySimpleNN(X_train_tensor)



# Define loop
for epoch in range(epochs):

# forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)
# loss caluclate
    loss = model.loss_function(y_pred, Y_train_tensor)
    print(f'Epochs: {epoch + 1}, Loss:{loss.item()}')

#backward pass
    loss.backward()

# parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

# zero gradients
    # model.weights.grad.zero()
    # model.bias.grad.zero()

#print loss
    print(f'Epochs: {epoch + 1}, Loss:{loss.item()}')

Epochs: 1, Loss:3.7903084114503605
Epochs: 1, Loss:3.7903084114503605
Epochs: 2, Loss:3.7798688668753977
Epochs: 2, Loss:3.7798688668753977
Epochs: 3, Loss:3.758913192633
Epochs: 3, Loss:3.758913192633
Epochs: 4, Loss:3.7271738014731675
Epochs: 4, Loss:3.7271738014731675
Epochs: 5, Loss:3.6848106546871047
Epochs: 5, Loss:3.6848106546871047
Epochs: 6, Loss:3.6319141538043853
Epochs: 6, Loss:3.6319141538043853
Epochs: 7, Loss:3.5682089654922318
Epochs: 7, Loss:3.5682089654922318
Epochs: 8, Loss:3.4933561354278453
Epochs: 8, Loss:3.4933561354278453
Epochs: 9, Loss:3.4070780523700446
Epochs: 9, Loss:3.4070780523700446
Epochs: 10, Loss:3.309695262401967
Epochs: 10, Loss:3.309695262401967
Epochs: 11, Loss:3.2001001597908534
Epochs: 11, Loss:3.2001001597908534
Epochs: 12, Loss:3.074715317744354
Epochs: 12, Loss:3.074715317744354
Epochs: 13, Loss:2.9367887927162144
Epochs: 13, Loss:2.9367887927162144
Epochs: 14, Loss:2.784921340753382
Epochs: 14, Loss:2.784921340753382
Epochs: 15, Loss:2.61829

In [37]:
# model.bias

In [38]:
# model.weights

## Model Evaluation

In [67]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5590950846672058
