In [19]:
import torch
import torch.nn as nn

In [22]:
# creating the model

class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out





In [23]:
# create dataset

features = torch.rand(10,5)

features.shape[1]

model = Model(features.shape[1])

model(features)

tensor([[0.5087],
        [0.5220],
        [0.4661],
        [0.4535],
        [0.4750],
        [0.5671],
        [0.4542],
        [0.4947],
        [0.4864],
        [0.4618]], grad_fn=<SigmoidBackward0>)

In [24]:
# show model weights

model.linear.weight



Parameter containing:
tensor([[-0.0194, -0.0460,  0.4472,  0.0998, -0.0245]], requires_grad=True)

In [25]:

model.linear.bias

Parameter containing:
tensor([-0.2037], requires_grad=True)

In [26]:
!pip install torchinfo

In [28]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [29]:
# create a Neural Network Of Hidden Layer

In [33]:
class Model2(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [34]:
features = torch.rand(10,5)

features.shape[1]

model = Model2(features.shape[1])

model(features)

tensor([[0.4919],
        [0.4991],
        [0.4676],
        [0.4772],
        [0.5039],
        [0.4859],
        [0.4802],
        [0.5018],
        [0.5048],
        [0.4766]], grad_fn=<SigmoidBackward0>)

In [36]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## using Nerual Network Contnaier

In [38]:
class Model3(nn.Module):
  def __init__(self,num_features):

    super().__init__()

    self.network = nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )


  def forward(self,features):

    out = self.network(features)

    return out