In [2]:
import torch

print(torch.__version__)



2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
else:
  print("GPU is not available, use CPU")

GPU is not available, use CPU


**CREATING A TENSOR**


In [4]:
#using Empty
a = torch.empty(2,3)

In [5]:
#check type

type(a)

torch.Tensor

In [6]:
#using zeros

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand

torch.rand(2,3)

tensor([[0.6417, 0.3108, 0.3383],
        [0.8600, 0.9669, 0.3424]])

In [9]:
# manual seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


TENSOR SHAPE


In [12]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068937142588943669, 3760569697577874736],
        [6498750548718008110, 7309453675965983778, 8315168162784306286]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

TENSOR DATA TYPES


In [18]:
  x.dtype

torch.int64

In [19]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [21]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |




Mathematical operations




SCALER OPERATIONS


In [23]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

Element wise opeations


In [25]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [27]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [28]:
c = torch.tensor([1, -2, 3, -4])

In [29]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [30]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [31]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [32]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [33]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [34]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [35]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

Reduction Operation




In [36]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e


tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [37]:
torch.sum(e)

tensor(28.)

In [39]:
torch.sum(e,dim=0)

tensor([16.,  5.,  7.])

In [40]:
torch.sum(e,dim=1)

tensor([ 7., 21.])

In [41]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([8.0000, 2.5000, 3.5000])

In [42]:
# median
torch.median(e)

tensor(5.)

In [43]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [44]:
# product
torch.prod(e)

tensor(0.)

In [45]:
# standard deviation
torch.std(e)

tensor(3.8297)

In [46]:
# variance
torch.var(e)

tensor(14.6667)

In [47]:
# argmax
torch.argmax(e)

tensor(3)

In [48]:
# argmin
torch.argmin(e)

tensor(1)

Matrix operations

In [51]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 9, 7],
        [9, 2, 6]])
tensor([[7, 7],
        [8, 3],
        [6, 1]])


In [52]:
# matrix multiplication
torch.matmul(f,g)


tensor([[170,  90],
        [115,  75]])

In [53]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [54]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 9],
        [9, 2],
        [7, 6]])

In [56]:
# calucalte determinant

h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

torch.det(h)

tensor(-112.0000)

In [57]:
# inverse
torch.inverse(h)

tensor([[ 0.5000, -0.3750,  0.0000],
        [-0.2143,  0.1250,  0.1429],
        [-0.2500,  0.3125,  0.0000]])

Comparison operations

In [58]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 8, 5],
        [6, 2, 9]])
tensor([[5, 0, 4],
        [2, 7, 1]])


In [59]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

 Special functions

In [60]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[1., 5., 4.],
        [4., 1., 1.]])

In [61]:
torch.log(k)

tensor([[0.0000, 1.6094, 1.3863],
        [1.3863, 0.0000, 0.0000]])

In [62]:
# exp
torch.exp(k)

tensor([[  2.7183, 148.4132,  54.5981],
        [ 54.5981,   2.7183,   2.7183]])

In [63]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 2.2361, 2.0000],
        [2.0000, 1.0000, 1.0000]])

In [64]:
# sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.9933, 0.9820],
        [0.9820, 0.7311, 0.7311]])

In [65]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0474, 0.9820, 0.9526],
        [0.9526, 0.0180, 0.0474]])

In [66]:
# relu
torch.relu(k)

tensor([[1., 5., 4.],
        [4., 1., 1.]])

## Inplace Operations

In [67]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1893, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])
tensor([[0.5224, 0.4175, 0.0340],
        [0.9157, 0.3079, 0.6269]])


In [68]:
m.add_(n)

tensor([[0.7117, 1.3361, 0.2472],
        [1.3114, 0.9096, 1.0504]])

In [69]:
m

tensor([[0.7117, 1.3361, 0.2472],
        [1.3114, 0.9096, 1.0504]])

In [70]:
n

tensor([[0.5224, 0.4175, 0.0340],
        [0.9157, 0.3079, 0.6269]])

In [73]:
m.relu_()

tensor([[0.7117, 1.3361, 0.2472],
        [1.3114, 0.9096, 1.0504]])

## Copying a Tensor

In [74]:
a = torch.rand(2,3)
a

tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

In [75]:
b = a

In [76]:
b

tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

In [77]:
b = a.clone()

In [78]:
b

tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

In [82]:
a[0][0] = 10

In [83]:
b

tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

In [85]:
a

tensor([[10.0000,  0.6594,  0.0887],
        [ 0.4890,  0.5887,  0.7340]])

## Reshaping Tensor


In [87]:
a = torch.ones(4,4)

In [88]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [89]:
#reshape

a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])